services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - flight-database:/var/lib/postgresql@16/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  flight-database:
